version: '3.8'

services:
  app:
    build: .
    container_name: trizzi_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=trizzi
      - POSTGRES_PASSWORD=trizzi123
      - POSTGRES_DB=trizzi_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - trizzi_net

  postgres:
    image: postgres:15-alpine
    container_name: trizzi_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=trizzi
      - POSTGRES_PASSWORD=trizzi123
      - POSTGRES_DB=trizzi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - trizzi_net

  redis:
    image: redis:7-alpine
    container_name: trizzi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - trizzi_net

volumes:
  pgdata:

networks:
  trizzi_net:
    driver: bridge 